### PR TITLE
Extend Container structure to expose all container environment variables

### PR DESCRIPTION
**Pull request by mrdrup**
This pull request will make all container variables accessible from template through `.Env` map
Also it extends basic templating functionality with a couple of string functions:
* *`replace $string $old $new $count`*: Replaces up to `$count` occurences of `$old` with `$new` in `$string`. Alias for [`strings.Replace`](http://golang.org/pkg/strings/#Replace)
* *`split $string $sep`*: Splits `$string` into a slice of substrings delimited by `$sep`. Alias for [`strings.Split`](http://golang.org/pkg/strings/#Split)
* *`splitN $string $sep $count`*: Splits `$string` into a slice of substrings delimited by `$sep`, with number of substrings returned determined by `$count`. Alias for [`strings.SplitN`](https://golang.org/pkg/strings/#SplitN)

Pretty much all extended functionality replicates original [docker-gen](https://github.com/jwilder/docker-gen) behaviour.

### CODE REVIEW

**Comment by codesuki** [comment]
Awesome! Thanks for contributing. I'll merge as soon as I get back to work.

**Comment by lucaschain** [comment]
That is really awesome!

**Comment by codesuki** [comment]
I'll merge it tomorrow! Sorry it took so long.

**Comment by codesuki** [comment]
Thanks again. I'll make a new version after merging the others. And again sorry it took so long.

**Pull request merged**
